// <auto-generated />
namespace BMSwebapi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changes22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes22));
        
        string IMigrationMetadata.Id
        {
            get { return "202008310747566_changes22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
